pub(crate) const MAX_REQUEST_BODY_BYTES: usize = 512 * 1024;

pub mod app;
pub mod attachment;
mod auto_compact;
mod auto_update;
pub mod code_nav;
pub mod config;
pub mod control;
pub mod conversation;
pub mod discovery;
pub mod events;
mod launch_directory;
pub mod machine;
pub mod mcp;
pub mod metrics;
pub mod old_sessions;
pub mod project;
#[cfg(feature = "pulse")]
pub mod pulse;
pub mod recovery;
pub mod registry;
mod registry_integration;
mod registry_web;
pub mod remote;
pub mod self_update;
pub mod session_search;
pub mod status;
pub mod summarizer;
mod summary;
pub mod supervisor;
mod systemd_scope;
pub mod tls;
pub mod tmux;
pub mod transcript;
pub mod ui;
pub mod web;
pub mod workspace;

pub mod github;
pub mod herodevs;
pub mod llm;
mod platform_http;
